[colors]
; Colores base extraídos de la imagen
background = #4D171f0d
window-background = #FF171f0d
background-alt = #68715c
foreground = #c5c7c2
border-color = #558429
primary = #558429
secondary = #688248
text = #c5c7c2
alert = #8d908b
disabled = #c5c7c2

; Colores "Aurora" mapeados a la paleta de pywal
aurora-blue = #9ba2a5
aurora-green = #72b137
aurora-yellow = #bcc1ba
aurora-orange = #8bae60
aurora-violet = #7788a9

; Opacidad	Hexadecimal
; 100% (Sólido)	FF
; 95%	F2
; 90%	E6
; 80%	CC
; 75%	BF
; 50%	80
; 45%	73	Equilibrio entre color y transparencia.
; 40%	66	El color del fondo de pantalla domina mucho.
; 30%	4D	Muy transparente, apenas un tinte de color.
; 20%	33	Casi invisible, solo para separar elementos.
; 10%	1A	Apenas un "fantasma" del color de fondo.
; 0% (Invisible)	00
