
;==================================================================
;
;    ██╗████████╗ ███████╗     ███████╗ ██████╗    ███████╗   ██████╗
;    ██║╚══██╔══╝   ██╔════╝      ██╔════╝  ██╔═══ ██╗  ██╔════╝    ██╔════╝
;    ██║   ██║      ███████╗     █████╗  ██║    ██║   ███████╗   ███████╗
;    ██║   ██║      ╚════██║      ██╔══╝    ██║    ██║   ╚════██║   ╚════██║
;    ██║   ██║      ███████║     ██║       ╚██████ ╔╝  ███████║   ███████║
;
;    This is a configuration, created from the default Polybar config.
;    Several New Modules are added to the default one.
;
;======================================================================

include-file = ~/.config/polybar/colors.ini

[bar/mybar]
# monitor = ${env:MONITOR:}
# monitor = HDMI-A-0
width = 97%
offset-x = 1.5%
offset-y = 1%
height = 22pt
radius = 15
fixed-center = true
fullscreen = true
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
border-size = 2.5pt
#border-color = ${colors.border-color}
border-color = ${colors.background}
padding-left = 0
padding-right = 0
module-margin-left = 0
module-margin-right = 0
separator = 
dim-value = 1.0
separator-foreground = ${colors.disabled}
font-0 = "JetBrains Mono:size=10;3"
font-1 = "monospace:size=10;2"
font-2 = "CaskaydiaCove Nerd Font:size=11;4"
font-3 = "CaskaydiaCove Nerd Font Mono:size=18;4"
modules-left =  mymenu sep bi ewmh bd sep bi xwindow bd sep bi network-menu bd sep tray 
modules-center = bi date bd sep bi pacupdate bd
modules-right = bi battery bd sep bi pulseaudio bd sep bi memory bd sep bi cpu bd sep bi cpu-temp bd sep bi gpu-temp bd sep bi magic-click bd sep sessionLogout
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
override-redirect = false
wm-restack = generic
#wm-name = xfce4-panel
#bottom = false

[module/tray]
type = internal/tray
format = <tray>
format-margin = 5pt
tray-spacing = 8px
tray-padding = 0px
tray-size = 65%


[module/bi]
type = custom/text
label = "%{T4}%{T-}"
label-foreground = ${colors.window-background}
label-background = ${colors.background}


[module/bd]
type = custom/text
label = "%{T4}%{T-}"
label-foreground = ${colors.window-background}
label-background = ${colors.background}

[module/sep]
type = custom/text
label = " "
label-foreground = ${colors.window-background}


[module/ewmh]
type = internal/xworkspaces
icon-default = 󰑊
format = <label-state>
format-background = ${colors.window-background}
format-font = 3
label-active ="%{T4}󰮯 %{T-}"
label-active-font = 4
#label-active-background = ${colors.background-alt}
label-active-foreground = ${colors.primary} 
label-active-padding = 2
label-occupied = "%{T4}󰊠 %{T-}"
label-occupied-font = 3
label-occupied-foreground = ${colors.aurora-green}
label-occupied-padding = 1
label-empty = "%{T4}󰑊 %{T-}"
label-empty-font = 3
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1
label-urgent = "%{T4}󰊠 %{T-}" 
label-urgent-font = 3
label-urgent-background = ${colors.primary}
label-urgent-padding = 1
enable-click = true
enable-scroll = true
pin-workspaces = false

[module/xwindow]
type = internal/xwindow
# label = %class:0:60:...%
label = %title:0:15:...%
label-maxlen = 20
padding = 5
format-background = ${colors.window-background}

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix-foreground = ${colors.primary}
format-volume = <ramp-volume> <label-volume> 
format-volume-background = ${colors.window-background}
label-volume = %{A3:~/.config/polybar/volume.sh:} %percentage%%%{A}
use-ui-max = false
label-muted = %{A3:~/.config/polybar/volume.sh:} Mute%{A}
label-muted-foreground = ${colors.disabled}
format-muted = <label-muted>
format-muted-prefix = 󰝟
format-muted-prefix-font = 2
format-muted-padding = 1
format-muted-background = ${colors.window-background}
ramp-volume-0 = 󰝟
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-3 = 
ramp-volume-4 =  
ramp-volume-5 = 
ramp-volume-6 = 
ramp-volume-7 =  
ramp-volume-8 =  
ramp-volume-9 =  
ramp-volume-foreground = ${colors.aurora-green}
ramp-volume-font = 2

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = %layout%
label-layout-foreground = ${colors.primary}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "%{A1:kitty btop:}%{T4}%{T-} RAM:%{A}"
label = "%{A1:kitty btop:} %percentage_used%%%{A}"
format-padding = 0.5
format-prefix-foreground = ${colors.aurora-orange}
format-background = ${colors.window-background}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "%{A1:kitty btop:}%{T4}%{T-} CPU:%{A}"
format-padding = 0.5
format-prefix-foreground = ${colors.primary}
label = "%{A1:kitty btop:}%percentage%%%{A}"
format-background = ${colors.window-background}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/network-menu]
type = custom/script
exec = ~/.config/polybar/network_speed.sh
interval = 5.0
format = <label>
format-connected-title = %{A1:networkmanager_dmenu:}%ssid%%{A}
format-background = ${colors.window-background}
format-foreground = ${colors.aurora-green}
format-padding = 0
format-margin = 0
label = %output%
label-font = 2
click-left = networkmanager_dmenu
click-middle = nmcli radio wifi on && notify-send "Wi-Fi Activado" "Conectando a: $(nmcli -t -f NAME connection show --active | head -n 1)"
click-right = nmcli radio wifi off

[module/eth]
inherit = network-base
interface-type = wired
label-connected = "%{F#53E8D4} %{F-}%downspeed:2% %{F#FF9535} %{F-}%upspeed:2%"
speed-unit = b/s
ping-intervel = 1
format-connected = <label-connected>
format-connected-prefix-font = 1
format-connected-padding = 1
format-disconnected = <label-disconnected>
format-disconnected-prefix = "󰈂 "
format-disconnected-prefix-font = 2
format-disconnected-padding = 1

[module/date]
type = internal/date
interval = 1
date = %I:%M %p
date-alt = "%{F#FF9535}%Y-%m-%d %I:%M:%S %p%{F-}"
label = %{A1:~/.config/polybar/calendar.sh:}%date%%{A}
label-font = 5
label-foreground = ${colors.aurora-green}
format = <label>
format-prefix = "%{T4}󱑂 %{T-}"
format-prefix-foreground = ${colors.primary}
format-prefix-font = 2
cursor-click = pointer
format-background = ${colors.window-background}

[module/battery]
type = internal/battery
battery = BAT1
adapter = AC
full-at = 98
low-at = 20
scroll-up = brightnessctl set +5%
scroll-down = brightnessctl set 5%-
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <animation-low> <label-low>

label-charging = %{A1:~/.config/polybar/battery.sh:}%percentage%%%{A}
label-discharging = %{A1:~/.config/polybar/battery.sh:}%percentage%%%{A}
label-full = %{A1:~/.config/polybar/battery.sh:}%percentage%%%{A}
label-low = %{A1:~/.config/polybar/battery.sh:}%percentage%%%{A}

format-charging-background = ${colors.window-background}
format-discharging-background = ${colors.window-background}
format-full-background = ${colors.window-background}
format-low-background = ${colors.window-background}

ramp-capacity-0 = "%{T4}󰂎%{T-}" 
ramp-capacity-1 = "%{T4}󰁻%{T-}"
ramp-capacity-2 = "%{T4}󰁾%{T-}"
ramp-capacity-3 = "%{T4}󰂀%{T-}"
ramp-capacity-4 = "%{T4}󰁹%{T-}"
ramp-capacity-foreground = ${colors.primary}
animation-charging-0 = "%{T4}󰂆%{T-}"
animation-charging-1 = "%{T4}󰂈%{T-}"
animation-charging-2 = "%{T4}󰂉%{T-}"
animation-charging-3 = "%{T4}󰂋%{T-}"
animation-charging-4 = "%{T4}󰂅%{T-}"
animation-charging-framerate = 750
animation-charging-foreground = ${colors.aurora-green}
animation-low-0 = "%{T4}󱃍%{T-}"
animation-low-1 = " "
animation-low-framerate = 500
animation-low-foreground = ${colors.alert}


[settings]
#screenchange-reload = true
#pseudo-transparency = true

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false

[module/cpu-temp]
type = internal/temperature
interval = 1
hwmon-path = ${env:HWMON_CPU:}
warn-temperature = 75
units = true
format = <ramp> <label>
format-background = ${colors.window-background}
format-padding = 0
format-warn = <ramp> <label-warn>
label = %temperature-c%
label-foreground = ${colors.aurora-green}
ramp-0 = " CPU:"
ramp-1 = " CPU:"
ramp-2 = " CPU:"
ramp-3 = " CPU:"


[module/gpu-temp]
type = internal/temperature
interval = 1
hwmon-path = ${env:HWMON_GPU:}
warn-temperature = 80
units = true
format = <ramp> <label>
format-background = ${colors.window-background}
format-warn = <ramp> <label-warn>
label = %temperature-c%
label-foreground = ${colors.aurora-blue}
ramp-0 = " GPU:"
ramp-1 = " GPU:"
ramp-2 = " GPU:"
ramp-3 = " GPU:"

#         󰌽   󰈸
[module/mymenu]
type = custom/text
format = <label>
format-padding = 2
label = "%{F#1A1B26}󰈸 Menu%{F-}" 
click-left = /home/$USER/.config/polybar/rofi.sh
format-background = ${colors.aurora-blue}
format-font = 3

[module/sessionLogout]
type = custom/text
format = <label>
format-padding = 1
label = "%{F#1A1B26}%{F-}"
click-left = /home/$USER/.config/polybar/logout.sh
format-background = ${colors.aurora-blue}
format-font = 4

[module/pacupdate]
type = custom/script
exec = /home/$USER/.config/polybar/mintupdates.sh
interval = 1000
label = %output%
format-font = 2
click-left = notify-send "Updates:" "$(mintupdate-cli list)"
format-background = ${colors.window-background}

[module/magic-click]
type = custom/text
format = <label>
format-background = ${colors.window-background}
label = " Magic"
click-left = /home/$USER/.config/polybar/rofi-wallpaper.sh
click-middle = notify-send "Uptime: " "$(uptime -p)"
click-right = /home/$USER/.config/polybar/rofi-themes.sh

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true
