#!/usr/bin/env python3
import dbus
import signal
import time
from unicodedata import east_asian_width

# ==========================================
# CONFIGURACIÓN
# ==========================================

# Longitud del texto en la Polybar antes de hacer scroll
message_display_len = 20

# Índice de fuente en tu config de Polybar (ej: font-5 es 6)
font_index = 6

# Velocidad de actualización del texto (segundos)
update_delay = 0.3

# Icono que abrirá/cerrará el widget de Eww
# Puedes cambiarlo por 󰎆 ,  , o el que prefieras
toggle_icon = ""

# Color para el icono (usando el formato de Polybar %{F#hex})
# He usado el azul ($blue) de tus otros widgets
icon_color = "#c2c4c7"

# Separador entre Título y Artista
metadata_separator = "-"

# Campos de metadatos a extraer
metadata_fields = ["xesam:title", "xesam:artist"]

# ==========================================
# LÓGICA DEL SCRIPT
# ==========================================

current_player_index = 0
player_names = []
players = []
message = ""
display_text = ""
status_paused = True

session_bus = dbus.SessionBus()

def get_player_name(service_name):
    return ".".join(service_name.split(".")[3:])

def update_players():
    global player_names, players, current_player_index
    
    # Listar todos los reproductores MPRIS disponibles
    all_services = [s for s in session_bus.list_names() if s.startswith('org.mpris.MediaPlayer2.')]
    
    active_player_found = False
    temp_players = []
    temp_names = []

    for service in all_services:
        obj = session_bus.get_object(service, '/org/mpris/MediaPlayer2')
        iface = dbus.Interface(obj, 'org.freedesktop.DBus.Properties')
        try:
            status = iface.Get('org.mpris.MediaPlayer2.Player', 'PlaybackStatus')
            temp_players.append(iface)
            temp_names.append(service)
            
            # Si encontramos uno reproduciendo, lo priorizamos
            if status == "Playing" and not active_player_found:
                current_player_index = len(temp_players) - 1
                active_player_found = True
        except:
            continue

    players = temp_players
    player_names = temp_names
    
    if not active_player_found and len(players) > 0:
        current_player_index = 0

def get_metadata():
    if not players: return {}
    try:
        return players[current_player_index].Get('org.mpris.MediaPlayer2.Player', 'Metadata')
    except:
        return {}

def get_status():
    if not players: return "Stopped"
    try:
        return players[current_player_index].Get('org.mpris.MediaPlayer2.Player', 'PlaybackStatus')
    except:
        return "Stopped"

def visual_len(text):
    visual_length = 0
    for ch in text:
        width = east_asian_width(ch)
        visual_length += 2 if width in ('W', 'F') else 1
    return visual_length

def make_visual_len(text, desired_len):
    res = ""
    curr = 0
    for char in text:
        if curr < desired_len:
            width = east_asian_width(char)
            curr += 2 if width in ('W', 'F') else 1
            res += char
        else:
            break
    return res + " " * (desired_len - curr)

def update_message():
    global message, display_text, status_paused
    
    if not players:
        tmp_msg = "____________________________"
        status_paused = True
    else:
        status = get_status()
        status_paused = (status != "Playing")
        meta = get_metadata()
        
        parts = []
        for field in metadata_fields:
            val = meta.get(field, "Unknown")
            if isinstance(val, dbus.Array) and len(val) > 0:
                val = val[0]
            parts.append(str(val))
        
        tmp_msg = f" {metadata_separator} ".join(parts)
        if visual_len(tmp_msg) > message_display_len:
            tmp_msg = " " + tmp_msg + " |"

    if message != tmp_msg:
        message = tmp_msg
        display_text = message

def scroll():
    global display_text
    if not status_paused and visual_len(display_text) > message_display_len:
        display_text = display_text[1:] + display_text[0]

def print_output():
    # Este comando verifica si la ventana 'music_test' está activa.
    # Si existe, mata el proceso eww. Si no, abre la ventana.
    eww_logic = "if eww active-windows | grep -q 'music_test'; then killall eww; else eww open music_test; fi"
    
    # Formateo para Polybar
    # %{A1:comando:} define la acción del clic izquierdo
    suffix = f" %{{F{icon_color}}}%{{A1:{eww_logic}:}}%{{T3}}{toggle_icon}%{{T-}}%{{A}} "
    
    scroll()
    text = make_visual_len(display_text, message_display_len)
    
    print(f"%{{T{font_index}}}{text}%{{T-}}{suffix}", flush=True)

def main():
    while True:
        update_players()
        update_message()
        print_output()
        time.sleep(update_delay)

if __name__ == '__main__':
    # Permite cambiar de reproductor manualmente enviando SIGUSR1 al proceso
    def handle_sig(sig, frame):
        global current_player_index
        if players:
            current_player_index = (current_player_index + 1) % len(players)
            
    signal.signal(signal.SIGUSR1, handle_sig)
    main()

# #!/usr/bin/env python3
# import dbus
# import signal
# import time
# from unicodedata import east_asian_width
#
# # Config options
#
# # (int) : Length of media info string. If length of string exceedes this value, the text will scroll. Default value is 20
# message_display_len = 20
#
# # (int) : Font index of polybar. this value should be 1 more than the font value specified in polybar config.
# font_index = 6
#
# # (float) : Update speed of the text in seconds.
# update_delay = 0.3
#
# # (list) : list of chars containing previous, play, pause, next glyphs for media controls in respective order
# control_chars = ['󰼨','󰼛','','󰼧']
#
# # (dict) : dict of char icons to display as prefix.
# # If player name is available as key, then use the corressponding icon,
# # else default key value.
# # example: 
# display_player_prefix = {
#     # "spotify":  '',
#     # "firefox":  '',
#     # "brave":  '',
#     # "default":  ''
#     "spotify":  '',
#     "firefox":  '',
#     "brave":  '',
#     "default":  ''
# }
#
# # (list) : list of metadata fields based on mpris sepecification.
# # For more details/ field names, refer [mpris sepecification](https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/)
# metadata_fields = ["xesam:title", "xesam:artist"]
#
# # (char) : separator for metadata fields
# metadata_separator = "-"
#
# # (bool) : Hide text when no player is available? True disables the output for no players.
# hide_output = False
#
# # Defult initialization
# current_player = None
# player_names = None
# players = None
# message = None
# display_text = ""
# display_prefix = ""
# display_suffix = ""
# last_player_name = None
#
# session_bus = dbus.SessionBus()
#
# def get_name(player_name ):
#     if player_name not in player_names:
#         return
#     name = ".".join(player_name.split(".")[3:])
#     return name
#
# def get_name_by_index(index):
#     if index >= len(player_names):
#         return
#     return get_name(player_names[index])
#
# def get_status(player):
#     status = ""
#     try:
#         status = player.Get('org.mpris.MediaPlayer2.Player', 'PlaybackStatus', dbus_interface='org.freedesktop.DBus.Properties')
#     except Exception as e:
#         pass
#     return status
#
# def get_metadata(player):
#     metadata = {}
#     try:
#         metadata = player.Get('org.mpris.MediaPlayer2.Player', 'Metadata', dbus_interface='org.freedesktop.DBus.Properties')
#     except Exception as e:
#         pass
#     return metadata
#
# def update_prefix_suffix(player_name="", status=""):
#     global display_prefix, display_suffix, status_paused
#
#     player_option = ""
#     if player_name != "":
#         player_option = "-p " + player_name
#
#     prev_button = "%%{A:playerctl %s previous :}%c%%{A}"    %(player_option,control_chars[0])
#     play_button = "%%{A:playerctl %s play :}%c%%{A}"        %(player_option,control_chars[1])
#     pause_button = "%%{A:playerctl %s pause :}%c%%{A}"      %(player_option,control_chars[2])
#     next_button = "%%{A:playerctl %s next :}%c%%{A}"        %(player_option,control_chars[3])
#
#     suffix = "| " + prev_button
#     if status == "Playing":
#         suffix += " "+pause_button
#         status_paused = False
#     else:
#         suffix += " "+play_button
#         status_paused = True
#     suffix += " "+next_button
#     # print(suffix)
#     display_suffix = suffix
#
#     for key in display_player_prefix.keys():
#         if key in player_name:
#             display_prefix = display_player_prefix[key]
#             break
#     else:
#         display_prefix = display_player_prefix["default"]
#
# def update_players():
#     global player_names, players, session_bus, current_player, last_player_name
#     player_names = [service  for service in session_bus.list_names() if service.startswith('org.mpris.MediaPlayer2.')]
#     players = [session_bus.get_object(service, '/org/mpris/MediaPlayer2') for service in player_names]
#     if last_player_name != get_name(current_player):
#         for index, player in enumerate(player_names):
#             if get_name(player) == last_player_name:
#                 current_player = index
#
# def handle_event(*args):
#     global current_player, players, last_player_name
#     update_players()
#     if len(players) == 0:
#         return
#     current_player += 1
#     current_player %= len(players)
#     last_player_name = get_name_by_index(current_player)
# #    print("SIGUSR1: updated values - current_player = %d  players len = %d"%(current_player,len(players)))
#
# def update_message():
#     global players, current_player,player_names, message, display_text, message_display_len, display_suffix, last_player_name
#     if len(players) == 0:
#         tmp_message = "No player available"
#         update_prefix_suffix()
#     else:
#         name = get_name_by_index(current_player)
#         status = get_status(players[current_player])
#         metadata_obj = get_metadata(players[current_player])
#         metadata_string_list = []
#         for field in metadata_fields:
#             result = metadata_obj.get(field)
#             if type(result) == dbus.Array and len(result) > 0:
#                 result = result[0]
#             if not result or (type(result) == dbus.Array and len(result) == 0):
#                 result = "No "+field.split(":")[1]
#             metadata_string_list.append(str(result))
#         metadata_string = (" "+metadata_separator+" ").join(metadata_string_list)
#         if visual_len(metadata_string) > message_display_len:
#             metadata_string = " " + metadata_string + " |"
#         update_prefix_suffix(name,status)
#         tmp_message = ""
#         if metadata_string:
#             tmp_message += str(metadata_string)
#         last_player_name = name
#     if message != tmp_message:
#         message = tmp_message
#         display_text = message
#
# def scroll():
#     global display_text, message_display_len, status_paused
#     if not status_paused:
#         if visual_len(display_text) > message_display_len:
#             display_text = display_text[1:] + display_text[0]
#         elif visual_len(display_text) < message_display_len:
#             display_text += " "*(message_display_len - len(display_text))
#
# def visual_len(text):
#     visual_length = 0
#     for ch in text:
#         width = east_asian_width(ch)
#         if width == 'W' or width == 'F':
#             visual_length += 2
#         visual_length += 1
#     return visual_length
#
# def make_visual_len(text, visual_desired_length):
#     visual_length = 0
#     altered_text = ''
#     for char in text:
#         if visual_length < visual_desired_length:
#             width = east_asian_width(char)
#             if width == 'W' or width == 'F':
#                 visual_length += 2
#             else:
#                 visual_length += 1
#             altered_text += char
#         else:
#             break
#     if visual_length == visual_desired_length + 1:
#         altered_text = altered_text[:-1] + ' '
#     elif visual_length < visual_desired_length:
#         altered_text += ' ' * (visual_desired_length - visual_length)
#     return altered_text
#
# def print_text():
#     global display_text, message_display_len, players, player_names, display_prefix, display_suffix
#     if hide_output and len(players)==0:
#         print("", flush = True)
#         return
#     scroll()
#     print(display_prefix + " " +
#         "%%{T%d}" % (font_index) +
#         make_visual_len(display_text, message_display_len) +
#         "%{T-}" + display_suffix, flush=True)
#
# def main():
#     global current_player, players
#     update_players()
#     current_player = 0
#     while True:
#         time.sleep(update_delay)
#         update_players()
#         update_message()
#         print_text()
#
# if __name__ == '__main__':
#     signal.signal(signal.SIGUSR1, handle_event)
#     main()
