# --- INTERFAZ DE USUARIO ---
"ui.background" = { }
"ui.text" = { fg = "#c2c2c6"}
"ui.window" = { fg = "#5b5b70" }
"ui.help" = { bg = "#5b5b70", fg = "#c2c2c6"}

"ui.statusline" = { fg = "#c2c2c6", bg = "#5b5b70" }
"ui.statusline.inactive" = { fg = "#707880", bg = "#0c0c1c"}
"ui.statusline.normal" = { fg = "#0c0c1c", bg = "#8F6044", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "#0c0c1c", bg = "#9B572A", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "#0c0c1c", bg = "#AC4A34", modifiers = ["bold"] }

"ui.virtual.indent-guide" = { fg = "#5b5b70" }
"ui.virtual.inlay-hint" = { fg = "#707880" }

# --- SOLUCIÓN AL CONTRASTE ---
"ui.selection" = { fg = "#0c0c1c", bg = "#8F6044" }
"ui.selection.primary" = { fg = "#0c0c1c", bg = "#B9A751" } # Un color distinto para la selección principal
"ui.cursor" = { fg = "#0c0c1c", bg = "#c2c2c6"}
"ui.cursor.match" = { fg = "#8F6044", modifiers = ["underline"] }

"ui.menu" = { fg = "#c2c2c6", bg = "#5b5b70" }
"ui.menu.selected" = { fg = "#0c0c1c", bg = "#8F6044" }
"ui.popup" = { bg = "#5b5b70" }
"ui.linenr" = { fg = "#707880" }
"ui.linenr.selected" = { fg = "#8F6044", modifiers = ["bold"] }

# --- SINTAXIS (Mapeo de lógica de colores) ---
"keyword" = "#8F6044"
"variable" = "#c2c2c6"
"variable.parameter" = "#c2c2c6"
"function" = "#8F6044"
"string" = "#9B572A"
"constant" = "#AC4A34"
"type" = "#AC4A34"
"comment" = { fg = "#707880", modifiers = ["italic"] }
"operator" = "#8F6044"
"punctuation" = "#707880"

# Diagnósticos
"error" = "#34544F"
"warning" = "#AC4A34"
"info" = "#8F6044"
"hint" = "#9B572A"

[palette]
# Colores base para uso rápido
theme_bg = "#0c0c1c"
theme_fg = "#c2c2c6"
accent = "#8F6044"
