# --- INTERFAZ DE USUARIO ---
"ui.background" = { }
"ui.text" = { fg = "#c2c5c7"}
"ui.window" = { fg = "#5d6971" }
"ui.help" = { bg = "#5d6971", fg = "#c2c5c7"}

"ui.statusline" = { fg = "#c2c5c7", bg = "#5d6971" }
"ui.statusline.inactive" = { fg = "#707880", bg = "#0d1920"}
"ui.statusline.normal" = { fg = "#0d1920", bg = "#6A6865", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "#0d1920", bg = "#3C434A", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "#0d1920", bg = "#4C4E50", modifiers = ["bold"] }

"ui.virtual.indent-guide" = { fg = "#5d6971" }
"ui.virtual.inlay-hint" = { fg = "#707880" }

# --- SOLUCIÓN AL CONTRASTE ---
"ui.selection" = { fg = "#0d1920", bg = "#6A6865" }
"ui.selection.primary" = { fg = "#0d1920", bg = "#8B847A" } # Un color distinto para la selección principal
"ui.cursor" = { fg = "#0d1920", bg = "#c2c5c7"}
"ui.cursor.match" = { fg = "#6A6865", modifiers = ["underline"] }

"ui.menu" = { fg = "#c2c5c7", bg = "#5d6971" }
"ui.menu.selected" = { fg = "#0d1920", bg = "#6A6865" }
"ui.popup" = { bg = "#5d6971" }
"ui.linenr" = { fg = "#707880" }
"ui.linenr.selected" = { fg = "#6A6865", modifiers = ["bold"] }

# --- SINTAXIS (Mapeo de lógica de colores) ---
"keyword" = "#6A6865"
"variable" = "#c2c5c7"
"variable.parameter" = "#c2c5c7"
"function" = "#6A6865"
"string" = "#3C434A"
"constant" = "#4C4E50"
"type" = "#4C4E50"
"comment" = { fg = "#707880", modifiers = ["italic"] }
"operator" = "#6A6865"
"punctuation" = "#707880"

# Diagnósticos
"error" = "#333946"
"warning" = "#4C4E50"
"info" = "#6A6865"
"hint" = "#3C434A"

[palette]
# Colores base para uso rápido
theme_bg = "#0d1920"
theme_fg = "#c2c5c7"
accent = "#6A6865"
