; ~/.config/polybar/bars/diagonal/config.ini
include-file = ~/.config/polybar/config-i3.ini

[bar/mybar]
inherit = bar/parent
width = 98%
offset-x = 1%
offset-y = 1%
height = 22pt
border-size = 2.5pt
radius = 0
border-color = ${colors.background}
line-size = 2pt

modules-left =  mymenu bd3 bd2 sep bi ewmh bd sep bi xwindow bd sep bi network-menu bd sep tray 
modules-center = bi date bd sep bi pacupdate bd
modules-right = bi battery bd sep bi pulseaudio bd sep bi memory bd sep bi cpu bd sep bi cpu-temp bd sep bi filesystem bd sep bi magic-click bd sep bi2 bi3 sessionLogout

; Si quieres cambiar los separadores a circulares solo para esta barra:

[module/bi]
type = custom/text
label = "%{T4}%{T-}"
label-foreground = ${colors.window-background}
label-background = ${colors.background}


[module/bd]
type = custom/text
label = "%{T4}%{T-}"
label-foreground = ${colors.window-background}
label-background = ${colors.background}

[module/bi2]
type = custom/text
label = "%{T4}%{T-}"
label-foreground = ${colors.aurora-blue}
label-background = ${colors.background}


[module/bd2]
type = custom/text
label = "%{T4}%{T-}"
label-foreground = ${colors.aurora-blue}
label-background = ${colors.background}

[module/bi3]
type = custom/text
label = "  "
label-background = ${colors.aurora-blue}


[module/bd3]
type = custom/text
label = "  "
label-background = ${colors.aurora-blue}
