[colors]
; Colores base extraídos de la imagen
background = #4D{background.strip}
window-background = #FF{background.strip}
background-alt = {color8}
foreground = {foreground}
border-color = {color2}
primary = {color2}
secondary = {color1}
text = {foreground}
alert = {color3}
disabled = {color15}

; Colores "Aurora" mapeados a la paleta de pywal
aurora-blue = {color12}
aurora-green = {color10}
aurora-yellow = {color11}
aurora-orange = {color9}
aurora-violet = {color13}

; Opacidad	Hexadecimal
; 100% (Sólido)	FF
; 95%	F2
; 90%	E6
; 80%	CC
; 75%	BF
; 50%	80
; 45%	73	Equilibrio entre color y transparencia.
; 40%	66	El color del fondo de pantalla domina mucho.
; 30%	4D	Muy transparente, apenas un tinte de color.
; 20%	33	Casi invisible, solo para separar elementos.
; 10%	1A	Apenas un "fantasma" del color de fondo.
; 0% (Invisible)	00
