# --- Backend de Rendimiento (Optimizado para AMD Radeon) ---
backend = "glx";
vsync = true;
use-damage = true;

# --- Animaciones v13 ---
animations = (
  {
    triggers = ["close"];
    opacity = {
      curve = "cubic-bezier(0,0,1,-0.28)";
      duration = .2; 
      start = "window-raw-opacity-before";
      end = 0;
    };
    blur-opacity = "opacity";
    shadow-opacity = "opacity";
    offset-x = "(1 - scale-x) / 2 * window-width";
    offset-y = "(1 - scale-y) / 2 * window-height";
    scale-x = {
      curve = "cubic-bezier(0,0,1,-0.28)";
      duration = .2;
      start = 1;
      end = .5;
    };
    scale-y = "scale-x";
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  },
  {
    triggers = ["show"];
      opacity = {
      curve = "cubic-bezier(0,1.28,1,1)";
      duration = .2;
      start = 0;
      end = "window-raw-opacity";
    }
    blur-opacity = "opacity";
    shadow-opacity = "opacity";
    offset-x = "(1 - scale-x) / 2 * window-width";
    offset-y = "(1 - scale-y) / 2 * window-height";
    scale-x = {
      curve = "cubic-bezier(0,1.28,1,1)";
      duration = .2;
      start = .5;
      end = 1;
    };
    scale-y = "scale-x";
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  },
  { 
    triggers = ["open"];
    opacity = {
      curve = "cubic-bezier(0,1.28,1,1)";
      duration = .2;
      start = 0;
      end = "window-raw-opacity";
    }
    blur-opacity = "opacity";
    shadow-opacity = "opacity";
    offset-x = "(1 - scale-x) / 2 * window-width";
    offset-y = "(1 - scale-y) / 2 * window-height";
    scale-x = {
      curve = "cubic-bezier(0,1.28,1,1)";
      duration = .2;
      start = .5;
      end = 1;
    };
    scale-y = "scale-x";
    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  },
  {
    triggers = ["geometry"]
    scale-x = {
      curve = "cubic-bezier(0,1.28,1,1)";
      duration = 0.22;
      start = "window-width-before / window-width";
      end = 1;
    }
    scale-y = {
      curve = "cubic-bezier(0,1.28,1,1)";
      duration = 0.22;
      start = "window-height-before / window-height";
      end = 1;
    }
    offset-x = {
      curve = "cubic-bezier(0,1.28,1,1)";
      duration = 0.22;
      start = "window-x-before - window-x";
      end = 0;
    }
    offset-y = {
      curve = "cubic-bezier(0,1.28,1,1)";
      duration = 0.22;
      start = "window-y-before - window-y";
      end = 0;
    }

    shadow-scale-x = "scale-x";
    shadow-scale-y = "scale-y";
    shadow-offset-x = "offset-x";
    shadow-offset-y = "offset-y";
  }
)# --- Sombras ---
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.5;
shadow-exclude = [
    "name = 'Notification'",
     "class_g = 'Polybar'",
    "_GTK_FRAME_EXTENTS@:c"
];

# --- Difuminado y Transparencia ---
# Si notas lento el sistema, cambia dual-kawase por kernel
# blur-method = "dual_kawase";
# blur-strength = 5;
# blur-background-fixed = true;
#
# blur-background-exclude = [
#     "class_g = 'slop'",
#     "class_g = 'Polybar'",
#     "_GTK_FRAME_EXTENTS@:c"
# ];

# inactive-opacity = 0.90;
# active-opacity = 1.0;
# frame-opacity = 1.0;

# --- Esquinas Redondeadas (Para que haga juego con tu Polybar) ---
# corner-radius = 15;
# rounded-corners-exclude = [
#     "window_type = 'dock'",
#     "window_type = 'desktop'"
# ];

# --- Desvanecimiento (Fading) ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;
